# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apis.dm_api_account import account_pb2 as apis_dot_dm__api__account_dot_account__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AccountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/AccountService/Login',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.LoginRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.LoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/AccountService/Logout',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.LogoutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.LogoutAll = channel.unary_unary(
                '/AccountService/LogoutAll',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.LogoutAllRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetCurrentAccount = channel.unary_unary(
                '/AccountService/GetCurrentAccount',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.GetCurrentAccountRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.GetCurrentAccountResponse.FromString,
                )
        self.GetAccounts = channel.unary_unary(
                '/AccountService/GetAccounts',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsResponse.FromString,
                )
        self.RegisterAccount = channel.unary_unary(
                '/AccountService/RegisterAccount',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountResponse.FromString,
                )
        self.ActivateAccount = channel.unary_unary(
                '/AccountService/ActivateAccount',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.ActivateAccountRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.ActivateAccountResponse.FromString,
                )
        self.ChangeAccountEmail = channel.unary_unary(
                '/AccountService/ChangeAccountEmail',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountEmailRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountEmailResponse.FromString,
                )
        self.ResetAccountPassword = channel.unary_unary(
                '/AccountService/ResetAccountPassword',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.ResetAccountPasswordRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.ResetAccountPasswordResponse.FromString,
                )
        self.ChangeAccountPassword = channel.unary_unary(
                '/AccountService/ChangeAccountPassword',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountPasswordRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountPasswordResponse.FromString,
                )
        self.UpdateAccount = channel.unary_unary(
                '/AccountService/UpdateAccount',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.UpdateAccountRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.UpdateAccountResponse.FromString,
                )
        self.RegisterAccountClientStream = channel.stream_unary(
                '/AccountService/RegisterAccountClientStream',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountClientStreamResponse.FromString,
                )
        self.GetAccountsServerStream = channel.unary_stream(
                '/AccountService/GetAccountsServerStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.User.FromString,
                )
        self.GetAccountsByLoginDuplexStream = channel.stream_stream(
                '/AccountService/GetAccountsByLoginDuplexStream',
                request_serializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsByLoginRequest.SerializeToString,
                response_deserializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsByLoginResponse.FromString,
                )


class AccountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAccountEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetAccountPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAccountPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAccountClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountsServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountsByLoginDuplexStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.LoginRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.LogoutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'LogoutAll': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutAll,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.LogoutAllRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCurrentAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentAccount,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.GetCurrentAccountRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.GetCurrentAccountResponse.SerializeToString,
            ),
            'GetAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccounts,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsResponse.SerializeToString,
            ),
            'RegisterAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAccount,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountResponse.SerializeToString,
            ),
            'ActivateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateAccount,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.ActivateAccountRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.ActivateAccountResponse.SerializeToString,
            ),
            'ChangeAccountEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAccountEmail,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountEmailRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountEmailResponse.SerializeToString,
            ),
            'ResetAccountPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetAccountPassword,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.ResetAccountPasswordRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.ResetAccountPasswordResponse.SerializeToString,
            ),
            'ChangeAccountPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAccountPassword,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountPasswordRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.ChangeAccountPasswordResponse.SerializeToString,
            ),
            'UpdateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccount,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.UpdateAccountRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.UpdateAccountResponse.SerializeToString,
            ),
            'RegisterAccountClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.RegisterAccountClientStream,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.RegisterAccountClientStreamResponse.SerializeToString,
            ),
            'GetAccountsServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAccountsServerStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.User.SerializeToString,
            ),
            'GetAccountsByLoginDuplexStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetAccountsByLoginDuplexStream,
                    request_deserializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsByLoginRequest.FromString,
                    response_serializer=apis_dot_dm__api__account_dot_account__pb2.GetAccountsByLoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/Login',
            apis_dot_dm__api__account_dot_account__pb2.LoginRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/Logout',
            apis_dot_dm__api__account_dot_account__pb2.LogoutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogoutAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/LogoutAll',
            apis_dot_dm__api__account_dot_account__pb2.LogoutAllRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCurrentAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/GetCurrentAccount',
            apis_dot_dm__api__account_dot_account__pb2.GetCurrentAccountRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.GetCurrentAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/GetAccounts',
            apis_dot_dm__api__account_dot_account__pb2.GetAccountsRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.GetAccountsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/RegisterAccount',
            apis_dot_dm__api__account_dot_account__pb2.RegisterAccountRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.RegisterAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActivateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/ActivateAccount',
            apis_dot_dm__api__account_dot_account__pb2.ActivateAccountRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.ActivateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeAccountEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/ChangeAccountEmail',
            apis_dot_dm__api__account_dot_account__pb2.ChangeAccountEmailRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.ChangeAccountEmailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetAccountPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/ResetAccountPassword',
            apis_dot_dm__api__account_dot_account__pb2.ResetAccountPasswordRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.ResetAccountPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeAccountPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/ChangeAccountPassword',
            apis_dot_dm__api__account_dot_account__pb2.ChangeAccountPasswordRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.ChangeAccountPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountService/UpdateAccount',
            apis_dot_dm__api__account_dot_account__pb2.UpdateAccountRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.UpdateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterAccountClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/AccountService/RegisterAccountClientStream',
            apis_dot_dm__api__account_dot_account__pb2.RegisterAccountRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.RegisterAccountClientStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountsServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AccountService/GetAccountsServerStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountsByLoginDuplexStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/AccountService/GetAccountsByLoginDuplexStream',
            apis_dot_dm__api__account_dot_account__pb2.GetAccountsByLoginRequest.SerializeToString,
            apis_dot_dm__api__account_dot_account__pb2.GetAccountsByLoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
