# generated by datamodel-codegen:
#   filename:  get_user.json
#   timestamp: 2023-08-26T14:20:48+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, StrictBool, StrictInt, StrictStr


class Rating(BaseModel):
    enabled: StrictBool
    quality: StrictInt
    quantity: StrictInt


class Info(BaseModel):
    value: StrictStr
    parseMode: StrictStr


class Paging(BaseModel):
    postsPerPage: StrictInt
    commentsPerPage: StrictInt
    topicsPerPage: StrictInt
    messagesPerPage: StrictInt
    entitiesPerPage: StrictInt


class Settings(BaseModel):
    colorSchema: StrictStr
    nannyGreetingsMessage: StrictStr
    paging: Paging


class Resource(BaseModel):
    login: StrictStr
    roles: List[StrictStr]
    mediumPictureUrl: StrictStr
    smallPictureUrl: StrictStr
    status: StrictStr
    rating: Rating
    online: StrictStr
    name: StrictStr
    location: StrictStr
    registration: StrictStr
    icq: StrictStr
    skype: StrictStr
    originalPictureUrl: StrictStr
    info: Info
    settings: Settings


class Model(BaseModel):
    resource: Resource
    metadata: StrictStr
