# generated by datamodel-codegen:
#   filename:  get_user.json
#   timestamp: 2023-08-27T09:58:44+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, StrictBool, StrictInt, StrictStr, Field


class Roles(Enum):
    GUEST = 'Guest'
    PLAYER = 'Player'
    ADMINISTRATOR = 'Administrator'
    NANNY_MODERATOR = 'NannyModerator'
    REGULAR_MODERATOR = 'RegularModerator'
    SENIOR_MODERATOR = 'SeniorModerator'


class Rating(BaseModel):
    enabled: StrictBool
    quality: StrictInt
    quantity: StrictInt


class Resource(BaseModel):
    login: StrictStr
    roles: List[Roles]
    medium_picture_url: StrictStr = Field(alias="mediumPictureUrl")
    small_picture_url: StrictStr = Field(alias="smallPictureUrl")
    status: StrictStr
    rating: Rating
    online: StrictStr
    name: StrictStr
    location: StrictStr
    registration: StrictStr


class UserEnvelope(BaseModel):
    resource: Resource
    metadata: StrictStr
